import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
// The pinned compiler cannot construct parameterized mu families.
// This generator specializes only application source, never compiler input at runtime.
const families = [
  ['Nats', 'seqNat', 'Nat', 'natsNil', 'natsCons', false],
  ['ByteStrings', 'seqBytes', 'Bytes', 'byteStringsNil', 'byteStringsCons', true],
  ['NatPairs', 'seqNatPair', 'prod (Nat, Nat)', 'natPairsNil', 'natPairsCons', true],
  ['ByteNatPairs', 'seqByteNatPair', 'prod (Bytes, Nat)', 'byteNatPairsNil', 'byteNatPairsCons', true],
  ['UnitsList', 'seqUnit', 'CodecUnit', 'unitsListNil', 'unitsListCons', true],
  ['NatLists', 'seqNatList', 'Nats', 'natListsNil', 'natListsCons', true],
];
function renderCollections(families) {
let output = '-- Generated by scripts/collections.mjs. Edit the shared template there.\n';
for (const [L, p, A, nil, cons, declare] of families) {
  if (declare) output += `
mu ${L} : Type 0 :=
| ${nil} : ${L}
| ${cons} (head : ${A}) (tail : ${L}) : ${L}
`;
  output += `
def ${p}Empty : ${L} := ${nil}
def ${p}Cons : ${A} -> ${L} -> ${L} := fun (head : ${A}) (tail : ${L}) => ${cons} head tail
def ${p}Head : ${L} -> ValueOption ${A.startsWith('prod') ? '(' + A + ')' : A} := fun (xs : ${L}) =>
  match xs as self in ${L} return ValueOption ${A.startsWith('prod') ? '(' + A + ')' : A} with
  | ${nil} => valueNone (${A})
  | ${cons} head tail => valueSome (${A}) head
def ${p}Tail : ${L} -> ${L} := fun (xs : ${L}) =>
  match xs as self in ${L} return ${L} with
  | ${nil} => ${nil}
  | ${cons} head tail => tail
def rec ${p}RevAcc : ${L} -> ${L} -> ${L} := fun (xs : ${L}) (acc : ${L}) =>
  match xs as self in ${L} return ${L} with
  | ${nil} => acc
  | ${cons} head tail => ${p}RevAcc tail (${cons} head acc)
def ${p}Reverse : ${L} -> ${L} := fun (xs : ${L}) => ${p}RevAcc xs ${nil}
def rec ${p}LengthAcc : ${L} -> Nat -> Nat := fun (xs : ${L}) (acc : Nat) =>
  match xs as self in ${L} return Nat with
  | ${nil} => acc
  | ${cons} head tail => ${p}LengthAcc tail (natAdd acc 1)
def ${p}Length : ${L} -> Nat := fun (xs : ${L}) => ${p}LengthAcc xs 0
def rec ${p}WriteAcc : ${L} -> (${A} -> Bytes) -> Bytes -> Bytes :=
  fun (xs : ${L}) (write : ${A} -> Bytes) (acc : Bytes) =>
    match xs as self in ${L} return Bytes with
    | ${nil} => reverse acc
    | ${cons} head tail => ${p}WriteAcc tail write (reverseOnto (write head) acc)
def ${p}Write : (${A} -> Bytes) -> ${L} -> Bytes :=
  fun (write : ${A} -> Bytes) (xs : ${L}) => ${p}WriteAcc xs write bytesNil
def rec ${p}Insert : ${L} -> (${A} -> ${A} -> Ordering) -> ${A} -> ${L} :=
  fun (xs : ${L}) (compare : ${A} -> ${A} -> Ordering) (value : ${A}) =>
    match xs as self in ${L} return ${L} with
    | ${nil} => ${cons} value ${nil}
    | ${cons} head tail =>
      match (compare value head) as compared in Ordering return ${L} with
      | orderLess => ${cons} value xs
      | orderEqual => ${cons} value xs
      | orderGreater => ${cons} head (${p}Insert tail compare value)
def rec ${p}SortScan : ${L} -> (${A} -> ${A} -> Ordering) -> ${L} :=
  fun (xs : ${L}) (compare : ${A} -> ${A} -> Ordering) =>
    match xs as self in ${L} return ${L} with
    | ${nil} => ${nil}
    | ${cons} head tail => ${p}Insert (${p}SortScan tail compare) compare head
def ${p}Sort : (${A} -> ${A} -> Ordering) -> ${L} -> ${L} :=
  fun (compare : ${A} -> ${A} -> Ordering) (xs : ${L}) => ${p}SortScan xs compare
def rec ${p}UniqScan : ${L} -> (${A} -> ${A} -> Ordering) -> ValueOption (${A}) -> ${L} -> ${L} :=
  fun (xs : ${L}) (compare : ${A} -> ${A} -> Ordering) (previous : ValueOption (${A})) (acc : ${L}) =>
    match xs as self in ${L} return ${L} with
    | ${nil} => ${p}Reverse acc
    | ${cons} head tail =>
      let duplicate : Nat :=
        case previous with
        | 0 (unit : prod ()) => 0
        | 1 (value : ${A}) =>
          match (compare value head) as compared in Ordering return Nat with
          | orderLess => 0
          | orderGreater => 0
          | orderEqual => 1
      in
      case (natEq duplicate 1) with
      | 0 (unit : prod ()) => ${p}UniqScan tail compare (valueSome (${A}) head) (${cons} head acc)
      | 1 (unit : prod ()) => ${p}UniqScan tail compare previous acc
def ${p}Uniq : (${A} -> ${A} -> Ordering) -> ${L} -> ${L} :=
  fun (compare : ${A} -> ${A} -> Ordering) (xs : ${L}) => ${p}UniqScan xs compare (valueNone (${A})) ${nil}
def ${p}Ops : ListOps (${A}) ${L} :=
  tuple (${p}Empty, ${p}Cons, ${p}Reverse, ${p}Length, ${p}Head, ${p}Tail, ${p}Write, ${p}Sort, ${p}Uniq)
`;
}
return output;
}
const cryptoFamilies = [
  ['Signatures', 'seqSignature', 'Signature', 'signaturesNil', 'signaturesCons', true],
  ['PublicKeys', 'seqPublicKey', 'PublicKey', 'publicKeysNil', 'publicKeysCons', true],
  ['Authorities', 'seqAuthority', 'Authority', 'authoritiesNil', 'authoritiesCons', true],
  ['AuthorityIds', 'seqAuthorityId', 'AuthorityId', 'authorityIdsNil', 'authorityIdsCons', true],
  ['HeaderDigests', 'seqHeaderDigest', 'HeaderDigest', 'headerDigestsNil', 'headerDigestsCons', true],
  ['BatchWorkers', 'seqBatchWorker', 'prod (BatchDigest, WorkerId)', 'batchWorkersNil', 'batchWorkersCons', true],
  ['AuthorityRounds', 'seqAuthorityRound', 'prod (AuthorityId, Round)', 'authorityRoundsNil', 'authorityRoundsCons', true],
  ['VoterEntries', 'seqVoterEntry', 'prod (AuthorityId, prod (Round, HeaderDigest))', 'voterEntriesNil', 'voterEntriesCons', true],
  ['AuthorityScores', 'seqAuthorityScore', 'prod (AuthorityId, Nat)', 'authorityScoresNil', 'authorityScoresCons', true],
  ['BatchDigests', 'seqBatchDigest', 'BatchDigest', 'batchDigestsNil', 'batchDigestsCons', true],
];
const vertexFamilies = [
  ['Batches', 'seqBatch', 'Batch', 'batchesNil', 'batchesCons', true],
  ['Votes', 'seqVote', 'Vote', 'votesNil', 'votesCons', true],
  ['Headers', 'seqHeader', 'Header', 'headersNil', 'headersCons', true],
  ['Certificates', 'seqCertificate', 'Certificate', 'certificatesNil', 'certificatesCons', true],
];
const consensusFamilies = [
  ['SubDags', 'seqSubDag', 'SubDag', 'subDagsNil', 'subDagsCons', true],
  ['LeaderCertificates', 'seqLeaderCertificate', 'prod (LeaderRound, Certificate)', 'leaderCertificatesNil', 'leaderCertificatesCons', true],
];
const machineFamilies = [
  ['ProposerActions', 'seqProposerAction', 'ProposerAction', 'proposerActionsNil', 'proposerActionsCons', true],
  ['ParentAggregators', 'seqParentAggregator', 'prod (Round, ParentAggregator)', 'parentAggregatorsNil', 'parentAggregatorsCons', true],
];
const nodeFamilies = [
  ['NodeCommands', 'seqNodeCommand', 'NodeCommand', 'nodeCommandsNil', 'nodeCommandsCons', true],
  ['NodeEvents', 'seqNodeEvent', 'NodeEvent', 'nodeEventsNil', 'nodeEventsCons', true],
];
const executionFamilies = [
  ['ConsensusBlocks', 'seqConsensusBlock', 'ConsensusBlock', 'consensusBlocksNil', 'consensusBlocksCons', true],
  ['ConsensusRecords', 'seqConsensusRecord', 'ConsensusRecord', 'consensusRecordsNil', 'consensusRecordsCons', true],
  ['ReplayRecords', 'seqReplayRecord', 'prod (ConsensusBlock, Batches)', 'replayRecordsNil', 'replayRecordsCons', true],
];
const simFamilies = [
  ['SimNodes', 'seqSimNode', 'prod (AuthorityId, ConsensusNode)', 'simNodesNil', 'simNodesCons', true],
  ['SimLogs', 'seqSimLog', 'prod (AuthorityId, SubDags)', 'simLogsNil', 'simLogsCons', true],
  ['SimStartups', 'seqSimStartup', 'prod (AuthorityId, NodeCommands)', 'simStartupsNil', 'simStartupsCons', true],
  ['SimQueue', 'seqSimQueue', 'prod (Nat, Nat, AuthorityId, NodeEvent)', 'simQueueNil', 'simQueueCons', true],
];
const storageFamilies = [['StorageSlots', 'seqStorageSlot', 'prod (U256, U256)', 'storageSlotsNil', 'storageSlotsCons', true]];
const stateFamilies = [
  ['Transfers', 'seqTransfer', 'Transfer', 'transfersNil', 'transfersCons', true],
  ['WorldAccounts', 'seqWorldAccount', 'prod (Address, Account)', 'worldAccountsNil', 'worldAccountsCons', true],
  ['GenesisEntries', 'seqGenesisEntry', 'prod (Address, GenesisAccount)', 'genesisEntriesNil', 'genesisEntriesCons', true],
  ['AddressBalances', 'seqAddressBalance', 'prod (Address, U256)', 'addressBalancesNil', 'addressBalancesCons', true],
];
for (const [name, group] of [['collections', families], ['crypto_collections', cryptoFamilies], ['vertex_collections', vertexFamilies], ['consensus_collections', consensusFamilies], ['machine_collections', machineFamilies], ['node_collections', nodeFamilies], ['execution_collections', executionFamilies], ['sim_collections', simFamilies], ['storage_collections', storageFamilies], ['state_collections', stateFamilies]]) {
  const output = renderCollections(group);
  const destination = resolve(root, `src/${name}.kan`);
  if (process.argv.includes('--check')) {
    if (readFileSync(destination, 'utf8') !== output) throw new Error(`Regenerate src/${name}.kan from scripts/collections.mjs.`);
    console.log(`${name}: specializations match the shared template.`);
  } else {
    writeFileSync(destination, output);
    console.log(`Generated ${group.length} concrete collection implementations in ${name}.kan.`);
  }
}
