import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
const destination=new URL('../src/crc32c_table.kan',import.meta.url);
const value=byte=>{
  let register=byte;
  for(let bit=0;bit<8;bit++)register=((register>>>1)^((register&1)?0x82f63b78:0))>>>0;
  return register;
};
const tree=(low,high,indent)=>{
  if(high-low===1)return String(value(low));
  const middle=(low+high)/2;
  return `case (natLt byte ${middle}) with\n${indent}| 1 (unit : prod ()) => (${tree(low,middle,indent+'  ')})\n${indent}| 0 (unit : prod ()) => (${tree(middle,high,indent+'  ')})`;
};
const text='-- Generated by scripts/crc32c-table.mjs.\n'+
  'def crc32cTable : Nat -> Nat := fun (byte : Nat) =>\n  '+tree(0,256,'  ')+'\n';
if(process.argv.includes('--check'))assert.equal(readFileSync(destination,'utf8'),text,'Regenerate the CRC-32C decision tree');
else writeFileSync(destination,text);
console.log('CRC-32C table: 256 total decision-tree leaves.');
