import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { compileOracle } from '../test/harness.mjs';
import { project } from './build.mjs';

const { runOracle } = compileOracle({ name: 'bn254-constants',
  sources: ['lib/evm/bn254_field.ml', 'lib/evm/bn254_curve.ml', 'lib/evm/secp256k1.ml'],
  modules: ['bn254_field.ml', 'bn254_curve.ml', 'secp256k1.ml'], packages: 'zarith', oracle: 'test/bn254-oracle.ml' });
const result = runOracle(['constants']);
assert.equal(result.status, 0, result.stderr);
const tables = new Map();
for (const line of result.stdout.trim().split('\n')) {
  const [name, index, c0, c1] = line.split(' ');
  assert.match(name, /^bnFrob(?:6C[12]|12C1)$/);
  assert.match(c0, /^\d+$/); assert.match(c1, /^\d+$/);
  const rows = tables.get(name) ?? []; assert.equal(Number(index), rows.length);
  rows.push([c0, c1]); tables.set(name, rows);
}
assert.deepEqual([...tables].map(([name, rows]) => [name, rows.length]), [['bnFrob6C1', 6], ['bnFrob6C2', 6], ['bnFrob12C1', 12]]);
const text = '-- Generated by scripts/generate-bn254.mjs from the pinned OCaml field powers.\n' + [...tables].map(([name, rows]) =>
  `def ${name} : Nat -> BnFq2 := fun (index : Nat) =>\n` + rows.map(([a, b], i) =>
    `  case (natEq index ${i}) with | 1 (unit : prod ()) => tuple (${a}, ${b}) | 0 (unit : prod ()) =>\n`).join('') + '  bn2One\n').join('');
const path = resolve(project, 'src/bn254_constants.kan');
if (process.argv.includes('--check')) assert.equal(readFileSync(path, 'utf8'), text, 'BN254 constants differ from pinned OCaml powers');
else writeFileSync(path, text);
console.log(`BN254 Frobenius tables ${process.argv.includes('--check') ? 'verified' : 'generated'}: 24 Fq2 coefficients.`);
