import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
// BLS12-381 parameters and G1 hash-to-curve suite from RFC 9380, section 8.8.1.
const prime=BigInt('0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab');
const order=BigInt('0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001');
const a=BigInt('0x144698a3b8e9433d693a02c96d4982b0ea985383ee66a8d8e8981aefd881ac98936f8da0e0f97f5cf428082d584c1d');
const b=BigInt('0x12e2908d11688030018b12e8753eee3b2016c1f0f24f4070a0b9c14fcef35ef55a23215a316ceaa5d1cc48e98e172be0');
const bytes=(value,width)=>{
  assert.ok(value>=0n&&value<1n<<BigInt(width*8),'constant does not fit its byte width');
  return 'b"'+value.toString(16).padStart(width*2,'0').match(/../g).map(byte=>'\\x'+byte).join('')+'"';
};
const power=(base,exponent)=>{let acc=1n;while(exponent>0n){if(exponent&1n)acc=acc*base%prime;base=base*base%prime;exponent>>=1n;}return acc;};
const mod=value=>(value%prime+prime)%prime;
const multiply2=([a,b],[c,d])=>[mod(a*c-b*d),mod(a*d+b*c)];
const power2=(base,exponent)=>{let acc=[1n,0n];while(exponent>0n){if(exponent&1n)acc=multiply2(acc,base);base=multiply2(base,base);exponent>>=1n;}return acc;};
const z=-0xd201000000010000n;
// Canonical G2 generator coordinates, in the real/imaginary basis used above.
const g2x=['024aa2b2f08f0a91260805272dc51051c6e47ad4fa403b02b4510b647ae3d1770bac0326a805bbefd48056c8c121bdb8',
  '13e02b6052719f607dacd3a088274f65596bd0d09920b61ab5da61bbdc7f5049334cf11213945d57e5ac7d055d042b7e'].map(value=>BigInt('0x'+value));
const g2y=['0ce5d527727d6e118cc9cdc6da2e351aadfd9baa8cbdd3a76d429a695160d12c923ac9cc3baca289e193548608b82801',
  '0606c4a02ea734cc32acd2b02bc28b99cb3e287e85a763af267492ab572e99ab3f370d275cec1da1aaa9075ff05f79be'].map(value=>BigInt('0x'+value));
assert.deepEqual(multiply2(g2y,g2y),multiply2(multiply2(g2x,g2x),g2x).map(value=>mod(value+4n)));
assert.equal(order,z**4n-z*z+1n);
assert.equal((z-1n)**2n*(prime**3n+z*prime*prime+(z*z-1n)*prime+z**3n-z)+3n,3n*(prime**4n-prime*prime+1n)/order);
assert.notEqual(order%3n,0n);
let source='-- Generated by scripts/generate-bls.mjs from the BLS12-381 parameters.\n';
for(const [name,value] of Object.entries({blsPrime:prime,blsOrder:order,blsHalf:(prime-1n)/2n,blsHalfInverse:(prime+1n)/2n,
  blsSwuA:a,blsSwuB:b,blsSwuMinusBOverA:prime-b*power(a,prime-2n)%prime,
  blsSwuExceptionalX:b*power(11n*a%prime,prime-2n)%prime,
  blsG1EffectiveCofactor:0xd201000000010001n})) source+=`def ${name} : Nat := ${value}\n`;
for(const [name,value,width] of [['blsSqrtExponent',(prime+1n)/4n,48],['blsOrderBytes',order,32],
  ['blsG1CofactorBytes',0xd201000000010001n,8],['blsCurveParameterBytes',-z,8],['blsCurveHalfParameterBytes',-z/2n,8],
  ['blsFinalExponent',(prime**12n-1n)/order,540]]) source+=`def ${name} : Bytes := ${bytes(value,width)}\n`;
for(const [name,exponent] of [['V',(prime-1n)/3n],['V2',2n*(prime-1n)/3n],['W',(prime-1n)/6n]]) {
  const [real,imaginary]=power2([1n,1n],exponent);
  source+=`def blsFrobenius${name} : prod (Nat, Nat) := tuple (${real}, ${imaginary})\n`;
}
for(const [name,[real,imaginary]] of [['X',g2x],['Y',g2y]])source+=`def blsG2Generator${name} : prod (Nat, Nat) := tuple (${real}, ${imaginary})\n`;
const isogeny=JSON.parse(readFileSync(new URL('./bls-isogeny.json',import.meta.url),'utf8'));
for(const [key,length] of [['xNumerator',12],['xDenominator',11],['yNumerator',16],['yDenominator',16]]) {
  assert.equal(isogeny[key].length,length);
  const coefficients=isogeny[key].map(hex=>BigInt('0x'+hex));
  assert.ok(coefficients.every(value=>value>=0n&&value<prime));
  source+=`def blsIso${key[0].toUpperCase()+key.slice(1)} : Nats := ${coefficients.reduce((tail,value)=>`natsCons ${value} (${tail})`,'natsNil')}\n`;
}
const path=fileURLToPath(new URL('../src/bls_constants.kan',import.meta.url));
if(process.argv.includes('--check')) assert.equal(readFileSync(path,'utf8'),source,'BLS constants differ from their generator');
else writeFileSync(path,source);
console.log('BLS12-381 scalar, field and exponent constants match their generator.');
