import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
// Fixed tuple projections for Keccak-f[1600], with lanes indexed x + 5*y.
// https://keccak.team/keccak_specs_summary.html
const offsets = [[0, 1, 62, 28, 27], [36, 44, 6, 55, 20], [3, 10, 43, 25, 39], [41, 45, 15, 21, 8], [18, 2, 61, 56, 14]];
const constants = ['1', '8082', '800000000000808a', '8000000080008000', '808b', '80000001', '8000000080008081', '8000000000008009',
  '8a', '88', '80008009', '8000000a', '8000808b', '800000000000008b', '8000000000008089', '8000000000008003',
  '8000000000008002', '8000000000000080', '800a', '800000008000000a', '8000000080008081', '8000000000008080', '80000001', '8000000080008008'];
const tuple = items => `tuple (${items.join(', ')})`;
const xor = (a, b) => `(wordXor64 ${a} ${b})`;
let text = '-- Generated by scripts/keccak.mjs from the Keccak-f[1600] lane equations.\n';
text += `def KeccakState : Type 0 := prod (${Array(25).fill('Nat').join(', ')})\n`;
text += `def keccakZero : KeccakState := ${tuple(Array(25).fill('0'))}\n`;
const zeroSum = Array.from({ length: 25 }, (_, i) => `a.${i}`).reduce((a, b) => `(natAdd ${a} ${b})`);
const zeroTest = `natEq ${zeroSum} 0`;
text += `def keccakStateIsZero : KeccakState -> Bool := fun (a : KeccakState) =>\n  ${zeroTest}\n`;
text += `def keccakRound : KeccakState -> Nat -> KeccakState := fun (a : KeccakState) (rc : Nat) =>\n`;
text += '  -- Theta, rho, pi and chi preserve zero; iota sets only the first lane.\n';
text += '  case (keccakStateIsZero a) with\n';
text += `  | 1 (unit : prod ()) => ${tuple(['wordXor64 0 rc', ...Array(24).fill('0')])}\n  | 0 (unit : prod ()) =>\n`;
for (let x = 0; x < 5; x++) text += `  let c${x} : Nat := ${Array.from({ length: 5 }, (_, y) => `a.${x + 5 * y}`).reduce(xor)} in\n`;
for (let x = 0; x < 5; x++) text += `  let d${x} : Nat := ${xor(`c${(x + 4) % 5}`, `(wordRotate64 c${(x + 1) % 5} 9223372036854775808 2)`)} in\n`;
for (let y = 0; y < 5; y++) for (let x = 0; x < 5; x++) {
  const offset = offsets[y][x];
  const value = xor(`a.${x + 5 * y}`, `d${x}`);
  const rotated = offset === 0 ? value : `(wordRotate64 ${value} ${1n << BigInt(64 - offset)} ${1n << BigInt(offset)})`;
  text += `  let b${y + 5 * ((2 * x + 3 * y) % 5)} : Nat := ${rotated} in\n`;
}
text += `  ${tuple(Array.from({ length: 25 }, (_, i) => {
  const x = i % 5, row = i - x;
  const value = xor(`b${i}`, `(wordAnd64 (natSub u64Max b${row + (x + 1) % 5}) b${row + (x + 2) % 5})`);
  return i === 0 ? xor(value, 'rc') : value;
}))}\n`;
text += 'def keccakPermute : KeccakState -> KeccakState := fun (initial : KeccakState) =>\n';
for (let i = 0; i < 24; i++) text += `  let s${i} : KeccakState := keccakRound ${i === 0 ? 'initial' : `s${i - 1}`} ${BigInt(`0x${constants[i]}`)} in\n`;
text += '  s23\n';
text += 'def keccakAbsorb : KeccakState -> Bytes -> KeccakState := fun (state : KeccakState) (block : Bytes) =>\n';
for (let i = 0; i < 17; i++) text += `  let lane${i} : prod (Nat, Bytes) := keccakReadWord ${i === 0 ? 'block' : `lane${i - 1}.1`} in\n`;
text += `  keccakPermute (${tuple(Array.from({ length: 25 }, (_, i) => i < 17 ? xor(`state.${i}`, `lane${i}.0`) : `state.${i}`))})\n`;
const path = fileURLToPath(new URL('../src/keccak_permutation.kan', import.meta.url));
if (process.argv.includes('--check')) {
  if (readFileSync(path, 'utf8') !== text) throw new Error('Regenerate src/keccak_permutation.kan with scripts/keccak.mjs.');
} else writeFileSync(path, text);
