import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Fixed opcode byte, constructor suffix and static gas cost from lib/evm.
const groups = [
  [0x00, 'Stop:0 Add:3 Mul:5 Sub:3 Div:5 Sdiv:5 Mod:5 Smod:5 Addmod:8 Mulmod:8 Exp:10 Signextend:5'],
  [0x10, 'Lt:3 Gt:3 Slt:3 Sgt:3 Eq:3 Iszero:3 And:3 Or:3 Xor:3 Not:3 Byte:3 Shl:3 Shr:3 Sar:3'],
  [0x20, 'Keccak256:30'],
  [0x30, 'Address:2 Balance:100 Origin:2 Caller:2 Callvalue:2 Calldataload:3 Calldatasize:2 Calldatacopy:3 Codesize:2 Codecopy:3 Gasprice:2 Extcodesize:100 Extcodecopy:100 Returndatasize:2 Returndatacopy:0 Extcodehash:100'],
  [0x40, 'Blockhash:20 Coinbase:2 Timestamp:2 Number:2 Prevrandao:2 Gaslimit:2 Chainid:2 Selfbalance:5 Basefee:2 Blobhash:3 Blobbasefee:2'],
  [0x50, 'Pop:2 Mload:3 Mstore:3 Mstore8:3 Sload:100 Sstore:0 Jump:8 Jumpi:10 Pc:2 Msize:2 Gas:2 Jumpdest:1 Tload:100 Tstore:100 Mcopy:3 Push0:2'],
  [0xf0, 'Create:0 Call:100 Callcode:100 Return:0 Delegatecall:100 Create2:0'],
  [0xfa, 'Staticcall:100'], [0xfd, 'Revert:0 Invalid:0 Selfdestruct:0'],
];
const fixed = groups.flatMap(([first, text]) => text.split(' ').map((entry, i) => {
  const [name, gas] = entry.split(':'); return { byte: first + i, name, gas: Number(gas) };
}));
const families = [
  { name: 'Push', type: 'PushBytes', min: 0x60, max: 0x7f, offset: 0x5f, wrap: 'pushBytesValue', unwrap: 'pushBytesNat', gas: 3 },
  { name: 'Dup', type: 'StackDepth', min: 0x80, max: 0x8f, offset: 0x7f, wrap: 'stackDepthValue', unwrap: 'stackDepthNat', gas: 3 },
  { name: 'Swap', type: 'StackDepth', min: 0x90, max: 0x9f, offset: 0x8f, wrap: 'stackDepthValue', unwrap: 'stackDepthNat', gas: 3 },
  { name: 'Log', type: 'TopicCount', min: 0xa0, max: 0xa4, offset: 0xa0, unwrap: 'topicCountNat', gas: 375 },
];
if (new Set(fixed.map(x => x.byte)).size !== fixed.length) throw new Error('Duplicate opcode byte');
const match = (name, result, fixedBody, familyBody) => `def ${name} : Opcode -> ${result} := fun (op : Opcode) => match op as self in Opcode return ${result} with\n` +
  [...fixed.map(x => `  | op${x.name} => ${fixedBody(x)}`), ...families.map(x => `  | op${x.name} n => ${familyBody(x)}`)].join('\n') + '\n';
let output = '-- Generated by scripts/opcodes.mjs. Edit the declarative opcode table there.\nmu Opcode : Type 0 :=\n' +
  [...fixed.map(x => `| op${x.name} : Opcode`), ...families.map(x => `| op${x.name} (n : ${x.type}) : Opcode`)].join('\n') + '\n';
output += match('opcodeEncode', 'Nat', x => x.byte, x => `natAdd ${x.offset} (${x.unwrap} n)`);
output += match('opcodeName', 'Bytes', x => `b"${x.name.toUpperCase()}"`, x => `append b"${x.name.toUpperCase()}" (decimal64 (${x.unwrap} n))`);
output += match('opcodeImmediateBytes', 'Nat', () => '0', x => x.name === 'Push' ? 'pushBytesNat n' : '0');
output += match('gasStaticCost', 'Nat', x => x.gas, x => x.gas);
output += 'def opcodeDecode : Nat -> ValueOption Opcode := fun (byte : Nat) =>\n';
for (const x of fixed) output += `  case (natEq byte ${x.byte}) with | 1 (unit : prod ()) => valueSome Opcode op${x.name}\n  | 0 (unit : prod ()) =>\n`;
for (const x of families) {
  output += `  case (boolAnd (boolNot (natLt byte ${x.min})) (natLt byte ${x.max + 1})) with\n  | 1 (unit : prod ()) => `;
  output += x.name === 'Log' ? `(${['topicZero', 'topicOne', 'topicTwo', 'topicThree'].map((name, i) => `case (natEq byte ${x.min + i}) with | 1 (unit : prod ()) => valueSome Opcode (opLog ${name}) | 0 (unit : prod ()) => `).join('')}valueSome Opcode (opLog topicFour))\n` : `valueSome Opcode (op${x.name} (${x.wrap} (natSub byte ${x.offset})))\n`;
  output += '  | 0 (unit : prod ()) =>\n';
}
output += '  valueNone Opcode\ndef opcodeEqual : Opcode -> Opcode -> Bool := fun (a : Opcode) (b : Opcode) => natEq (opcodeEncode a) (opcodeEncode b)\n';
const destination = fileURLToPath(new URL('../src/opcode.kan', import.meta.url));
if (process.argv.includes('--check')) {
  if (readFileSync(destination, 'utf8') !== output) throw new Error('Regenerate src/opcode.kan from scripts/opcodes.mjs.');
  console.log('Opcode definitions match the declarative table.');
} else { writeFileSync(destination, output); console.log(`Generated ${fixed.length} fixed opcodes and four operand families.`); }
