import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const lock = JSON.parse(readFileSync(resolve(root, 'source-lock.json'), 'utf8'));
const coverage = {
  'lib/std/nonempty.ml': 'Ported: generic operations with typed collection dictionaries, src/nonempty.kan; OCaml differential tests',
  'lib/std/prng.ml': 'Ported: full-width SplitMix64, split and signed inclusive ranges, src/prng.kan; OCaml differential tests',
  'lib/codec/bcs.ml': 'Ported: primitive and composite codecs, refinement, enums, list/map/set canonicality, src/bcs.kan, src/codec.kan, src/sequence.kan; OCaml differential tests',
  'lib/crypto_stub/tn_crypto.ml': 'Ported simulation profile: BLAKE2s, keys, signatures and aggregates, src/crypto_stub.kan; OCaml differential tests',
  'lib/hash32/hash32.ml': 'Partial: checked bytes, zero, equality, ordering and hex, src/fixed.kan; Keccak conversion awaits Keccak type',
  'lib/types/round.ml': 'Partial: scalar operations; Map/Set pending, src/scalars.kan',
  'lib/types/leader_round.ml': 'Ported with explicit exhaustion correction, src/scalars.kan and src/scalar_ops.kan',
  'lib/types/units.ml': 'Ported value operations with explicit overflow corrections, unsigned decimal transport and checked Address, src/scalars.kan, src/scalar_ops.kan, src/fixed.kan',
  'lib/types/authority_id.ml': 'Partial: checked identifiers, hash derivation, equality/order and internal signer sets; general Map/Set API pending',
  'lib/types/authority.ml': 'Ported: identity, keys, addresses and unit voting power, src/crypto_stub.kan',
  'lib/types/committee.ml': 'Ported: canonical roster, thresholds, indexing, stake and equality, src/committee.kan; OCaml differential tests',
  'lib/types/digests.ml': 'Ported: distinct nominal digest kinds and zero values, src/fixed.kan',
  'lib/types/batch.ml': 'Ported: batch/sealed values, codec, simulation digest, receipt metadata and limits, src/batch.kan; golden and OCaml differential tests',
  'lib/types/block_num_hash.ml': 'Ported: anchor values, codec and signed comparison, src/block_num_hash.kan; OCaml differential tests',
  'lib/vertex/intent.ml': 'Ported: consensus intent prefix, src/vote.kan',
  'lib/vertex/header.ml': 'Ported: canonical fields, codec, digest and validation, src/header.kan; golden and OCaml differential tests',
  'lib/vertex/vote.ml': 'Ported: signing, claims and verification, src/vote.kan; OCaml differential tests',
  'lib/vertex/certificate.ml': 'Ported: assembly, claims, genesis membership and aggregate verification, src/certificate.kan; OCaml differential tests',
};
const text = `# Port roadmap and source map

Baseline: telcoin-ocaml ${lock.upstream.revision}, chunk 44.
source-lock.json records every selected source file and each library's dune
declaration, including its dependencies. This table is generated by
\`node scripts/roadmap.mjs\`; its statuses describe implemented coverage,
not a claim of complete module parity.

## Milestones

| Milestone | Scope and acceptance evidence | Status |
| --- | --- | --- |
| 0 | Pin the chunk-44 source and compiler, compile reusable Wasm, port scalar/primitive-codec core, compare exact outputs and failures with OCaml, provide a working CLI. | Implemented; see VALIDATION.md. |
| 1 | Complete tn_std, tn_codec and tn_types. Add general codecs, scalars, SplitMix64, digests, authorities, committees, batches and anchors. Match vectors and constructor rejections. | Value and codec behavior tested. General Round/Authority Map/Set APIs remain. |
| 2 | Port tn_vertex and tn_consensus pure state machines, plus deterministic tn_sim and the CLI. Compare complete seeded output transcripts. | Vertex values, validation and simulation crypto tested. Consensus DAG, reducers, scheduling and simulator are next. |
| 3 | Timing, consensus recovery and tn_execution. Compare durable-before-action transitions, restart transcripts and consensus-chain hashes. | Planned |
| 4 | tn_state and EVM ALU/interpreter, then environment, access/refund, storage, calls, creation and transaction execution. Preserve full U256 arithmetic, gas, rollback and fork-specific outcomes. | Planned |
| 5 | RLP, Keccak, trie/state roots, transaction envelopes, signatures and source-supported precompiles. Reuse existing golden fixtures; compare acceptance, output, gas and errors separately. | Planned |
| 6 | Batch validation, executed blocks, engine, driver, registry and epoch transitions. Compare complete committed/executed output and checkpoint consistency. | Planned |
| 7 | Durable file framing, logs, locks and checkpoints. Audit the host's fsync, atomic replacement, locking and recovery guarantees before porting the IO shell. Test interrupted writes and restart behavior. | Planned |
| 8 | tn_network and Snappy pure codecs through chunk 44, then integrate source-supported crypto implementations and shells. Compare wire vectors, canonicality, corruption and size-limit cases. | Planned |

Milestones 4 and 5 overlap at hash/state/transaction dependencies and should be
split into dependency-ordered increments before implementation. The goal is
parity with the current OCaml source. Implementing transport or node behavior
missing from that source is a separate extension.

## Implementation decisions

- Use the standard Kanon compiler and WasmGC ABI. Do not add application
  primitives to the compiler to conceal port gaps.
- Keep protocol transitions in Kanon and IO in an explicit host shell.
  The current Wasm module has no host imports.
- Keep both source checkouts unchanged. No source is fetched during tests.
- Record exact source hashes and the compiler executable hash. Do not infer
  executable provenance from a nearby compiler source revision.
- Preserve ordinary OCaml behavior and record corrections independently.
  Round exhaustion and host-int addition overflow are documented in README.md.
- Port a library seam with meaningful positive and negative comparisons
  before marking that seam complete. A successful build alone is insufficient.

## Outstanding design work

Kanon's primitives have add/subtract/multiply/compare but no division or bitwise
operations. Bounded division, wrapping words, SplitMix64 and BLAKE2s are ordinary
Kanon code. Production BLAKE3/BLS and U256 still need performance and
representation work. Simulation signatures are forgeable and cannot
authenticate a real node.

Kanon does not currently provide OCaml .mli-style constructor hiding. Review
how checked values are admitted at every external boundary. Nominal types and
opaque Wasm references do not by themselves prove the smart-constructor
invariants or establish a cross-module security boundary.

General Nonempty and BCS combinators use erased type parameters and typed
collection dictionaries. The compiler cannot construct parameterized recursive
families. scripts/collections.mjs generates 15 concrete carriers from one
template. Zero-byte codec units use a nominal nullary type to avoid a backend
trap with polymorphic empty-product payloads. Generated insertion sort is
quadratic; production-size collection performance remains unvalidated.

The next acceptance target is the source simulator: port the DAG, leader
schedule, vote/parent aggregation, voter/proposer, Bullshark, sub-DAG and node
reducers, then compare complete seeded event/output transcripts. No consensus
agreement or liveness claim follows from vertex validation alone.

## Library inventory

| Source library | Implementation modules | Implementation lines |
| --- | ---: | ---: |
${lock.upstream.libraries.map(l => `| ${l.name} | ${l.modules} | ${l.implementationLines} |`).join('\n')}

## Implementation module status

| OCaml source | Kanon status |
| --- | --- |
${lock.upstream.files.filter(f => f.path.startsWith('lib/') && f.path.endsWith('.ml')).map(f => `| ${f.path} | ${coverage[f.path] ?? 'Pending'} |`).join('\n')}
`;
writeFileSync(resolve(root, 'PORTING.md'), text);
console.log('Wrote PORTING.md from the pinned source inventory.');
